alias sshDevLogin='sshpass -f '/home/nandakumar/Documents/Doopaadoo/Internal/dev/password.txt' ssh nandakumard@192.168.1.53'
alias sshTestLogin='sshpass -f '/home/nandakumar/Documents/Doopaadoo/Internal/test/password.txt' ssh nandakumard@192.168.1.56'
alias sshVcmsLogin='sshpass -f '/home/nandakumar/Documents/Doopaadoo/Internal/vcms/password.txt' ssh nandakumard@192.168.1.54'
alias addEnv='scripts/add_new_env.sh'
alias pushEnvToS3='scripts/push_to_s3.sh'
